name: CI
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_DB: attendance
          POSTGRES_USER: attendance_user
          POSTGRES_PASSWORD: attendance_pass
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U attendance_user -d attendance"
          --health-interval 5s --health-timeout 5s --health-retries 20

    env:
      DATABASE_URL: postgresql://attendance_user:attendance_pass@localhost:5432/attendance
      JWT_SECRET_KEY: test-secret
      API_KEY_APP: ci-key
      SIGNING_SECRET: ci-secret

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff black

      - name: Load schema (db/init.sql)
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends postgresql-client
          PGPASSWORD=attendance_pass psql -h localhost -U attendance_user -d attendance -f db/init.sql

      - name: Lint
        run: ruff check .

      - name: Format check
        run: black --check .

      - name: Tests
        run: pytest -q
